"""
constrained_output.py — schema-valid JSON enforcement (§3.2 item 6, Protocol Compliance;
also the Safety & Protocol 10% line: "structured schema adherence, and valid state
payloads").

>>> UPDATED: confirmed local LLM, not a hosted API <<<
Since the team is running a self-hosted model with direct logits access, `XGrammarBackend`
below is now the PRIMARY, recommended path — not a maybe. XGrammar (arXiv:2411.15100) masks
the token-probability distribution during decoding, guaranteeing the output matches your
JSON Schema by construction (near-zero overhead per XGrammar's own benchmarks), which is a
strictly stronger guarantee than `ValidateRepairBackend`'s generate-then-retry loop. Use
`XGrammarBackend` for anything generated by your own local model. Keep
`ValidateRepairBackend` around only as (a) a fallback if `xgrammar` can't be installed on
someone's dev machine in time, or (b) a safety net around any THIRD-PARTY output you don't
control the logits of (e.g. if a tool call ever routes through an external API).

>>> HONESTY NOTE — I could not execute XGrammarBackend end-to-end <<<
Everything else in this repo (clarifier.py, visual_buffer.py, adapter.py) was run against
your real test suite and is confirmed passing (271/271). `XGrammarBackend` below is written
directly from XGrammar's current documented API (xgrammar.mlc.ai — TokenizerInfo,
GrammarCompiler, GrammarCompiler.compile_json_schema, xgr.contrib.hf.LogitsProcessor,
confirmed against their Quick Start and JSON Generation docs), but I couldn't pip-install
`xgrammar` or load a real model in this sandbox to actually run it end-to-end. Test it
against your real model before trusting it in the demo — specifically check: (1) that
`TokenizerInfo.from_huggingface` accepts your tokenizer's vocab_size without a mismatch
(padding-token vocab size vs. config.vocab_size is a common gotcha per their own docs),
and (2) that `compile_json_schema` accepts a plain JSON Schema dict the way I'm calling it
here (their docs show both a Pydantic model and a JSON schema *string* — I'm passing
`json.dumps(schema)`, which matches their string path, but confirm on your model/version).

>>> WHERE THIS FITS RELATIVE TO MODULE 3 <<<
Module 3's own event factories (module3/runtime/events/*.py) already Pydantic-validate the
*event envelope* — a `make_final_response(...)` call cannot produce a malformed
FinalResponsePayload, that's covered. What this file is for is the layer BELOW that: turning
a raw LLM completion into the plain dict you then pass into `make_final_response(text=...,
state_snapshot=...)` or `make_clarification(...)`. It's the seam between "the local model
generated some tokens" and "valid arguments to a Module 3 factory function" — most useful to
whoever in Module 2 is parsing tool-call arguments or final-response text out of the model's
output, not a replacement for anything Module 3 already does.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Callable, Optional, Protocol

try:
    import jsonschema  # pip install jsonschema
    _HAS_JSONSCHEMA = True
except ImportError:
    _HAS_JSONSCHEMA = False


class SchemaEnforcementError(Exception):
    """Raised when a backend cannot produce a schema-valid payload within its budget.
    Callers (agent.py) MUST catch this and degrade to a safe fallback response rather than
    emitting an invalid payload — an invalid payload is a direct Safety & Protocol hit,
    a caught exception with a canned fallback is not."""


class GenerateFn(Protocol):
    """Signature every backend expects for the underlying model call.
    prompt: str -> raw text completion (Backend 2), or unused (Backend 1 drives generation
    itself via logits_processor and only needs a HF `model` + `tokenizer`, not this fn)."""
    def __call__(self, prompt: str) -> str: ...


@dataclass
class EnforcementResult:
    payload: dict[str, Any]
    attempts: int
    backend: str


class ValidateRepairBackend:
    """Schema-validate-and-repair loop for hosted-API LLMs. See module docstring."""

    def __init__(self, max_retries: int = 2):
        if not _HAS_JSONSCHEMA:
            raise ImportError(
                "ValidateRepairBackend needs `jsonschema` (pip install jsonschema). "
                "This is a much lighter dependency than XGrammar/llguidance — that's the "
                "point of using this backend when you don't have local logits access."
            )
        self.max_retries = max_retries

    def enforce(self, schema: dict, generate_fn: GenerateFn, base_prompt: str) -> EnforcementResult:
        prompt = base_prompt
        last_error: Optional[str] = None

        for attempt in range(1, self.max_retries + 2):  # +1 for the first non-retry attempt
            raw = generate_fn(prompt)
            candidate = self._extract_json(raw)

            if candidate is None:
                last_error = "response did not contain a parseable JSON object"
            else:
                try:
                    jsonschema.validate(instance=candidate, schema=schema)
                    return EnforcementResult(payload=candidate, attempts=attempt, backend="validate_repair")
                except jsonschema.ValidationError as e:
                    last_error = e.message

            prompt = (
                f"{base_prompt}\n\n"
                f"Your previous response was invalid: {last_error}\n"
                f"Respond with ONLY a single JSON object matching this schema, "
                f"no prose, no markdown fences:\n{json.dumps(schema)}"
            )

        raise SchemaEnforcementError(
            f"Failed to obtain schema-valid JSON after {self.max_retries + 1} attempts. "
            f"Last error: {last_error}"
        )

    @staticmethod
    def _extract_json(raw: str) -> Optional[dict]:
        raw = raw.strip()
        # Strip markdown code fences if the model added them despite instructions.
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.lower().startswith("json"):
                raw = raw[4:]
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            # Last resort: find the first {...} span and try that.
            start, end = raw.find("{"), raw.rfind("}")
            if start != -1 and end != -1 and end > start:
                try:
                    return json.loads(raw[start:end + 1])
                except json.JSONDecodeError:
                    return None
            return None


class XGrammarBackend:
    """True grammar-constrained decoding. Requires local logits access (confirmed: this
    team has it). Reference: Dong et al., "XGrammar: Flexible and Efficient Structured
    Generation Engine for Large Language Models" (arXiv:2411.15100). API confirmed against
    current xgrammar.mlc.ai docs (Quick Start, JSON Generation) as of this writing — see
    module docstring's honesty note on what I could NOT verify by actually running it.

    Usage — the one-time, per-process setup (do this ONCE, not per turn):

        from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
        model_id = "your/local-model"
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(model_id, ...)
        config = AutoConfig.from_pretrained(model_id)
        backend = XGrammarBackend(tokenizer, vocab_size=config.vocab_size)

    Then, per turn, either use the high-level `generate()` (recommended — handles the
    compile-cache, logits_processor wiring, and decode/parse for you):

        result = backend.generate(FINAL_RESPONSE_SCHEMA, model, tokenizer, prompt)
        # result.payload is already a parsed, schema-valid dict

    ...or, if you need lower-level control over the `model.generate(...)` call (custom
    sampling params, batching, etc.), pull just the processor:

        processor = backend.make_logits_processor(FINAL_RESPONSE_SCHEMA)
        output_ids = model.generate(**inputs, logits_processor=[processor], ...)
    """

    def __init__(self, tokenizer, vocab_size: int, max_threads: int = 4):
        import xgrammar as xgr  # pip install xgrammar ; local-inference only, see docstring
        self._xgr = xgr
        self._tokenizer = tokenizer
        self.tokenizer_info = xgr.TokenizerInfo.from_huggingface(tokenizer, vocab_size=vocab_size)
        self.compiler = xgr.GrammarCompiler(self.tokenizer_info, max_threads=max_threads)
        self._compiled_cache: dict[str, Any] = {}

    def _compiled_for(self, schema: dict):
        # Cache by schema content, not object identity — the same logical schema
        # (e.g. FINAL_RESPONSE_SCHEMA used every turn) should only be compiled once for
        # the lifetime of this backend. Compilation is the expensive part; XGrammar's own
        # docs note matching against an already-compiled grammar is near-zero overhead.
        key = json.dumps(schema, sort_keys=True)
        if key not in self._compiled_cache:
            self._compiled_cache[key] = self.compiler.compile_json_schema(json.dumps(schema))
        return self._compiled_cache[key]

    def make_logits_processor(self, schema: dict):
        """Returns a HF-compatible logits_processor for `model.generate(...,
        logits_processor=[...])`, matching xgr.contrib.hf.LogitsProcessor's documented
        integration pattern. Use this if you need to control the generate() call yourself
        (batching, custom sampling); otherwise prefer `generate()` below."""
        compiled = self._compiled_for(schema)
        return self._xgr.contrib.hf.LogitsProcessor(compiled)

    def generate(
        self,
        schema: dict,
        model,
        tokenizer,
        prompt: str,
        max_new_tokens: int = 512,
        **generate_kwargs: Any,
    ) -> EnforcementResult:
        """High-level convenience: runs model.generate() under the grammar constraint,
        decodes, and parses the JSON for you. Since XGrammar constrains the token
        distribution DURING sampling, the output is schema-valid by construction — no
        validate-and-retry loop needed here (unlike ValidateRepairBackend), so this either
        succeeds or raises SchemaEnforcementError on a genuine decode/parse bug, not on a
        schema mismatch (that shouldn't be possible with the grammar correctly applied)."""
        processor = self.make_logits_processor(schema)
        model_inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=max_new_tokens,
            logits_processor=[processor],
            **generate_kwargs,
        )
        new_tokens = generated_ids[0][len(model_inputs.input_ids[0]):]
        raw_text = tokenizer.decode(new_tokens, skip_special_tokens=True)
        try:
            payload = json.loads(raw_text)
        except json.JSONDecodeError as e:
            # Should be rare-to-never with a correctly applied grammar constraint — if you
            # see this in practice, it points at a bug in the grammar/tokenizer wiring
            # (e.g. vocab_size mismatch), not at the model "getting it wrong".
            raise SchemaEnforcementError(
                f"XGrammar-constrained output failed to parse as JSON — this suggests a "
                f"grammar/tokenizer wiring bug, not a model error. Raw output: {raw_text!r}. "
                f"Underlying error: {e}"
            )
        return EnforcementResult(payload=payload, attempts=1, backend="xgrammar")


def enforce_json_schema(
    schema: dict,
    generate_fn: GenerateFn,
    base_prompt: str,
    backend: Optional[ValidateRepairBackend] = None,
) -> EnforcementResult:
    """Convenience entrypoint for the ValidateRepairBackend path (generate_fn is a plain
    str->str callable). If you're using XGrammarBackend instead, call
    `XGrammarBackend.generate(schema, model, tokenizer, prompt)` directly — its signature
    needs the model/tokenizer, not a generate_fn, since it has to inject the
    logits_processor into model.generate() itself. This function's default
    (ValidateRepairBackend) remains useful as a fallback / for any non-local-model calls
    your team makes (e.g. an external tool that itself wraps an API)."""
    backend = backend or ValidateRepairBackend()
    return backend.enforce(schema, generate_fn, base_prompt)
